### ISSUE TITLE
Failed to install on aarch64 device

### ISSUE THREAD

**Issue by luisfsr** [adbenitez/deltachat-cursed#12]
Hello! Cool project! I tried to install on a pinephone but the installation failed. Is there any architecture limitation?

**Comment by adbenitez** [comment]
hello :) the issue is with [deltachat python bindings](https://github.com/deltachat/deltachat-core-rust/tree/master/python) prebuild binaries that are not available for your platform.

You could try to compile deltachat core for your platform yourself, read this: https://github.com/deltachat/deltachat-core-rust/blob/master/python/README.rst

Alternatively you could ask at https://github.com/deltachat/deltachat-core-rust/ for more prebuilds to be generated, but seems this is difficult for them to automate, ideally there could be prebuilds even for Raspberry Pi so it would be a breeze to install deltachat core.
   
SIDE NOTE: I have been busy with deltachat bots development and my custom dc apk, and haven't even used this project in a while it probably will not work with current dc core. Sorry, I hope to get some time to update and improve it, it is just a work in progress.

Best regards,
adb.

**Comment by adbenitez** [comment]
GOOD NEWS!!! now there are Delta Chat Python wheels for aarch64 in https://m.devpi.net/dc/master, to install:

```
$ sudo pip3 install --pre -i https://m.devpi.net/dc/master deltachat
```
